### ISSUE TITLE
Missing FirebaseFirestoreSwift product

### ISSUE THREAD

**Issue by tylerjbarnes** [akaffenberger/firebase-ios-sdk-xcframeworks#16]
When pulling in the official Firebase package directly, there is a product called `FirebaseFirestoreSwift` available that adds support for the `@DocumentID` property wrapper, and `Codable` based write methods like `.setData(from: Codable)`.

Would it be possible to include that product in this package?

**Comment by akaffenberger** [comment]
It appears the `FirebaseFirestoreSwift` product is not in the Github release archive (ie the Firebase.zip). However it might still be possible to workaround that using [ZipBuilder](https://github.com/firebase/firebase-ios-sdk/tree/master/ReleaseTooling). Theoretically the script could be modified to clone the repo, generate the missing binary via ZipBuilder and include it. I'd need to do some more investigating since I'm not familiar with tooling.

**Comment by tylerjbarnes** [comment]
I see - thanks for the response! I'll look into the ZipBuilder option for manually bringing that in as a separate dependency. I see now that `FirebaseFirestoreSwift` is still marked as beta, so makes sense it wouldn't be in the release zip.

**Comment by WillBishop** [comment]
Is there any update to this? I'm trying to make sense of ZipBuilder, but if someone has done the work already that'd be awesome

**Comment by sejr** [comment]
Wanted to follow up on this -- @akaffenberger I see FirebaseFirestoreSwift in the release assets for 9.0.0, but don't see it as a Package Product when I go to add this dependency?

**Comment by sejr** [comment]
Looks like it's just included in FirebaseFirestore library as of 9.0.0!

With the fix for #26, I'm able to get everything running fine.

<img width="797" alt="Screen Shot 2022-05-16 at 3 12 33 PM" src="https://user-images.githubusercontent.com/2413031/168665470-b256c6db-4d83-423c-b2e4-42a2dfcc1fda.png">
<img width="809" alt="Screen Shot 2022-05-16 at 3 12 20 PM" src="https://user-images.githubusercontent.com/2413031/168665468-9b6c515e-c5a7-498e-ae55-09e70e14560f.png">

Before and after on my build time in GH Actions. This is a lifesaver 😄

**Comment by akaffenberger** [comment]
@sejr You are correct, as of 9.0.0 it's now an added dependency to the FirebaseFirestore target, so it should work out of the box. 

To test (and for reference in case others need it), I added a quick [Firestore example](https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/blob/master/iOS%20Example/iOS%20Example/Views/FirestoreView.swift) to this project, which uses the swift Codable features and property wrapper.

**Comment by akaffenberger** [comment]
@sejr Thank you for the tip jar recommendation! I added a link for it here: https://github.com/akaffenberger/buy-me-a-coffee
