### ISSUE TITLE
InAppMessaging bundle is missing

### ISSUE THREAD

**Issue by michalciurus** [akaffenberger/firebase-ios-sdk-xcframeworks#23]
`8.15.0 - [Firebase/InAppMessaging][I-IAM400009] Display ran into error for message 3978956120715808093: Error Domain=com.firebase.inappmessaging.display Code=1 "(null)" UserInfo={message=resource bundle is missing}`

![Screenshot 2022-04-26 at 12 30 27](https://user-images.githubusercontent.com/9080186/165280838-17372047-fde7-4fcb-b314-e4d84064ffe9.png)

I can't get the in app messages to work.

How are `.bundles` working with SPM and Firebase? 

Firebase _seems_ to be using, for getting the resources for `InAppMessaging`

```
+ (NSArray *)relevantBundles {
  return @[ [NSBundle mainBundle], [NSBundle bundleForClass:[self class]] ];
}
```

Correct me if I'm wrong: SPM puts all the resources into the main app bundle, but `mainBundle` called from `.xcframework` won't be the app bundle, it'll be the framework bundle, hence it can't find the needed resources. That's as far as I've gone with my investigation.

I'm trying to understand how to fix this issue as we really enjoy using this mirror. Could it have regressed? Or maybe I configured something incorrectly.

**Comment by michalciurus** [comment]
```
RESOURCE_PATH="${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk-xcframeworks/Sources/FirebaseInAppMessaging/Resources/"

FILENAME_IN_BUNDLE=InAppMessagingDisplayResources.bundle

BUILD_APP_DIR=${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}

rm -R "$BUILD_APP_DIR/$FILENAME_IN_BUNDLE"

if [ "$CONFIGURATION" == "Debug" ]; then
    cp -R "$RESOURCE_PATH/$FILENAME_IN_BUNDLE" "$BUILD_APP_DIR/$FILENAME_IN_BUNDLE"
else
    cp -R "$RESOURCE_PATH/$FILENAME_IN_BUNDLE" "$BUILD_APP_DIR/$FILENAME_IN_BUNDLE"
fi
```

I added this run script to fix the problem.

**Comment by akaffenberger** [comment]
Thank you for calling this out @michalciurus!

From what I can gather, you more or less found [the source of the issue](https://github.com/firebase/firebase-ios-sdk/blob/eb30b6fdd809cbfe3a9eb7f3ccf1dd46326bef2d/FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m#L59).

The framework is searching for `InAppMessagingDisplayResources.bundle` inside the main bundle. However, SPM creates a bundle per target inside the main bundle, so the actual path ends up being `Firebase_FirebaseInAppMessagingTarget.bundle/InAppMessagingDisplayResources.bundle`.

[Apple recommends using](https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package) `Bundle.module` when searching for resources from with an SPM framework. I haven't tested this, but the ObjC equivalent should be something like:
```
NSBundle *bundle = [NSBundle bundleWithURL: [SWIFTPM_MODULE_BUNDLE urlForResource:@"InAppMessagingDisplayResources" withExtension:@"bundle"]];
```

I will try to fork the firebase-ios-sdk this weekend and test this out, but for now I'd say your script is a decent workaround.

**Comment by akaffenberger** [comment]
Follow up -- unfortunately because it's a pre-built binary, `Bundle.module` is not available. As as a binaryTarget(), the framework gets embedded statically inside the main bundle. In short, there is no way for it to find the resources without the exact path being hard-coded programmatically, which isn't a possibility for us since this is a wrapper project.

The solutions as I see it:
1. Use a build script as you currently have, except modify it to iterate over each Firebase_Firebase<...>.bundle and move the contained resources directly into the main bundle.
2. Remove all resources from the `Package.swift` file, and update the readme to include an extra installation step, which would be to manually drag and drop any resource from the swift package into the xcode project.

I think #2 is the safer solution, since it doesn't rely on names/file structures which may change.

In the meantime, I created a SwiftPM pitch to allow for including resources directly in the main bundle, maybe it will get some traction:
https://forums.swift.org/t/swiftpm-binary-target-resource-bundles/57178

**Comment by akaffenberger** [comment]
As per above discussion, I made the following changes: 
- Excluded resource files in the Package.swift, since that was not behaving as expected
- Added a new script to automatically add resources to the main bundle
- Added instructions to the readme for using the new script, or alternatively dragging and dropping resources directly into the project

PR: https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/pull/25

**Comment by michalciurus** [comment]
Thank you @akaffenberger for such a swifty turnaround! Me and our team really appreciate the work you're doing.
