### ISSUE TITLE
Combine community extensions missing

### ISSUE THREAD

**Issue by ncltg** [akaffenberger/firebase-ios-sdk-xcframeworks#52]
The packages `FirebaseAuthCombine-Community` & `FirebaseFirestoreCombine-Community` that are part of the official Firebase SDK are not included into the `Package.swift` of this repository.

https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift

Line 65:
```
    ...
    .library(
      name: "FirebaseAuthCombine-Community",
      targets: ["FirebaseAuthCombineSwift"]
    ),
    .library(
      name: "FirebaseFirestoreCombine-Community",
      targets: ["FirebaseFirestoreCombineSwift"]
    ),
    ...
```

I am wondering if there is a specific limitation that prevent us from including those into the `FirebaseFirestore` and `FirebaseAuth` targets ?

**Comment by akaffenberger** [comment]
Hi, thanks for the feedback @ncltg! 

So the issue here is that the repo is using the frameworks directly from Firebase's Github releases. A script is downloading the [Firebase.zip](https://github.com/firebase/firebase-ios-sdk/releases/download/10.3.0/Firebase.zip) asset folder and generating a Package.swift file from it. 

As such, it unfortunately has the same limitation as [integrating those frameworks manually](https://firebase.google.com/docs/ios/installation-methods#integrate-manually) -- not all frameworks are available in their binary release.

The README.md within the Firebase.zip mentions this limitation:
> For the samples that depend on SDKs not
included in this archive, you'll need to use CocoaPods or use the
[ZipBuilder](https://github.com/firebase/firebase-ios-sdk/tree/master/ReleaseTooling)
to create your own custom binary frameworks.

Theoretically, we could modify this repo to use the zip builder tool for the missing binaries, but that work isn't something I currently have time for. It may be faster to create an issue against the original Firebase repo requesting the Combine extensions be included in the binary releases.
